### ISSUE TITLE
Add member Bug

### ISSUE THREAD

**Issue by Callhimbeast** [dbc2201/TIC#2]
After filling in the personal details, and then taking the photograph of the client and uploading it, the personal details vanish as if nothing had been entered there

**Comment by dbc2201** [comment]
Bug acknowledged. Steps to recreate -
1. Open Add Member Activity from Dashboard Activity.
2. Fill up the add member form.
3. Open camera from the camera button on the form.
3. Upon returning to the form, the values are gone.

**Comment by dbc2201** [comment]
Bug fixed in apk iter:3.
