### ISSUE TITLE
add member back bug

### ISSUE THREAD

**Issue by Callhimbeast** [dbc2201/TIC#3]
from the add member activity, the back button goes to login screen,from there pressing back button doesnt exit the app instead dashboard opens

**Comment by dbc2201** [comment]
Bug description inconclusive, please elaborate!

**Comment by dbc2201** [comment]
Bug acknowledged. Steps to reproduce -
1. Open AddMember Activity from Dashboard Activity.
2. Press physical/on screen back button from the AddMemberActivity.
3. MainActivity opens up, on pressing back again, the MainActivity falls into an infinite loop.
