### ISSUE TITLE
photograph bug

### ISSUE THREAD

**Issue by Callhimbeast** [dbc2201/TIC#4]
photograph captured shown if seen in landscape or potrait mode,but if you change the orientation photograph vanishes. Same is the case if the phone is in potrait mode the photgraph is shown ,but if you change the orientation photo disappers

Steps to reproduce
1 open the FAB on Dashboard Activity, Add Member Activity opens.
2 Take picture and fill in the personal details in the form on the activity.
3 The default orientation is portrait, so try changing the orientation to landscape.
4 Photograph disappears but personal details are intact

**Comment by dbc2201** [comment]
Bug could not be reproduced. Closed until further inspection.
