### ISSUE TITLE
Bug in imgBtn_joining_date #5

### ISSUE THREAD

**Issue by Callhimbeast** [dbc2201/TIC#9]
When the user clicks on imgbtn_joining_date again, the previous input values do not clear from the editText.
Steps to reproduce -
1. open dashboard activity
2.click on the FAB to open the add member form
3.scroll down to the joining date edit text
4. from the imgBtn choose any date
5. in the edit text the choosen date appears
6. if we choose any other date without clearing the previous date,the edit text displays both the dates,without clearing the date choosen in step 4.

**Comment by dbc2201** [comment]
Bug acknowledged, fix applied. Submitted for re-testing and regression.
